### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by webbertakken** [sbussard/canvas-sketch#15]
Project doesn't have a license.

I've forked your repository and converted the functionality to work with a Lean Project Canvas. However i noticed there is no license allowing me to do that in the first place.

I'd like to ask your permission to keep my [fork](https://github.com/CuriousInc/lean-project-canvas-sketch).

Additionally i think it is good for future reference to have an explicit license for the project.

**Comment by sbussard** [comment]
This code is free as in `libertarian`

![](https://media.giphy.com/media/jL0c2TrfDUz9S/giphy.gif )

PRs are welcome if that is unsettling to anyone.

**Comment by webbertakken** [comment]
Would the [MIT license](https://opensource.org/licenses/MIT) cover that for you? I could send you a PR.

**Comment by sbussard** [comment]
Sure! It says MIT in package.json but there may be a better source of truth

**Comment by sbussard** [comment]
Added a license. Thanks for the prompt. :)

**Comment by sbussard** [comment]
@webbertakken Also, very nice job with the Lean Project Canvas! 
Thanks for making and sharing that!
